language: go

matrix:
  include:
    - before_install:
        - cd services/matchmaking/queue
      env:
        global:
          - GO111MODULE=on 

go:
- "1.13.5"

git:
  depth: 1

notifications:
  email: false

script:
  - go test -v -race ./...
  