// Code generated by protoc-gen-go. DO NOT EDIT.
// source: custom_match.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCustomMatchRequest struct {
	Leader               uint64   `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	MaxUsers             uint32   `protobuf:"varint,4,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCustomMatchRequest) Reset()         { *m = AddCustomMatchRequest{} }
func (m *AddCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*AddCustomMatchRequest) ProtoMessage()    {}
func (*AddCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{0}
}

func (m *AddCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomMatchRequest.Unmarshal(m, b)
}
func (m *AddCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *AddCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomMatchRequest.Merge(m, src)
}
func (m *AddCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_AddCustomMatchRequest.Size(m)
}
func (m *AddCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomMatchRequest proto.InternalMessageInfo

func (m *AddCustomMatchRequest) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *AddCustomMatchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCustomMatchRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddCustomMatchRequest) GetMaxUsers() uint32 {
	if m != nil {
		return m.MaxUsers
	}
	return 0
}

type AddCustomMatchResponse struct {
	Users                []uint64 `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	MaxUsers             uint32   `protobuf:"varint,2,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	Leader               uint64   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCustomMatchResponse) Reset()         { *m = AddCustomMatchResponse{} }
func (m *AddCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*AddCustomMatchResponse) ProtoMessage()    {}
func (*AddCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{1}
}

func (m *AddCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomMatchResponse.Unmarshal(m, b)
}
func (m *AddCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *AddCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomMatchResponse.Merge(m, src)
}
func (m *AddCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_AddCustomMatchResponse.Size(m)
}
func (m *AddCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomMatchResponse proto.InternalMessageInfo

func (m *AddCustomMatchResponse) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AddCustomMatchResponse) GetMaxUsers() uint32 {
	if m != nil {
		return m.MaxUsers
	}
	return 0
}

func (m *AddCustomMatchResponse) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

type DeleteCustomMatchRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomMatchRequest) Reset()         { *m = DeleteCustomMatchRequest{} }
func (m *DeleteCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomMatchRequest) ProtoMessage()    {}
func (*DeleteCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{2}
}

func (m *DeleteCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomMatchRequest.Unmarshal(m, b)
}
func (m *DeleteCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomMatchRequest.Merge(m, src)
}
func (m *DeleteCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomMatchRequest.Size(m)
}
func (m *DeleteCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomMatchRequest proto.InternalMessageInfo

func (m *DeleteCustomMatchRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteCustomMatchRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type DeleteCustomMatchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomMatchResponse) Reset()         { *m = DeleteCustomMatchResponse{} }
func (m *DeleteCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomMatchResponse) ProtoMessage()    {}
func (*DeleteCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{3}
}

func (m *DeleteCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomMatchResponse.Unmarshal(m, b)
}
func (m *DeleteCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomMatchResponse.Merge(m, src)
}
func (m *DeleteCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomMatchResponse.Size(m)
}
func (m *DeleteCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomMatchResponse proto.InternalMessageInfo

type GetAllCustomMatchRequest struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Skip                 uint32   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllCustomMatchRequest) Reset()         { *m = GetAllCustomMatchRequest{} }
func (m *GetAllCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllCustomMatchRequest) ProtoMessage()    {}
func (*GetAllCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{4}
}

func (m *GetAllCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCustomMatchRequest.Unmarshal(m, b)
}
func (m *GetAllCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *GetAllCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCustomMatchRequest.Merge(m, src)
}
func (m *GetAllCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllCustomMatchRequest.Size(m)
}
func (m *GetAllCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCustomMatchRequest proto.InternalMessageInfo

func (m *GetAllCustomMatchRequest) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetAllCustomMatchRequest) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type GetAllCustomMatchResponse struct {
	Groups               []*CustomMatchGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAllCustomMatchResponse) Reset()         { *m = GetAllCustomMatchResponse{} }
func (m *GetAllCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCustomMatchResponse) ProtoMessage()    {}
func (*GetAllCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{5}
}

func (m *GetAllCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCustomMatchResponse.Unmarshal(m, b)
}
func (m *GetAllCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *GetAllCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCustomMatchResponse.Merge(m, src)
}
func (m *GetAllCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCustomMatchResponse.Size(m)
}
func (m *GetAllCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCustomMatchResponse proto.InternalMessageInfo

func (m *GetAllCustomMatchResponse) GetGroups() []*CustomMatchGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CustomMatchGroup struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Leader               uint64   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	PasswordRequired     bool     `protobuf:"varint,4,opt,name=password_required,json=passwordRequired,proto3" json:"password_required,omitempty"`
	MaxUsers             uint32   `protobuf:"varint,5,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	TotalUsers           uint32   `protobuf:"varint,6,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomMatchGroup) Reset()         { *m = CustomMatchGroup{} }
func (m *CustomMatchGroup) String() string { return proto.CompactTextString(m) }
func (*CustomMatchGroup) ProtoMessage()    {}
func (*CustomMatchGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{6}
}

func (m *CustomMatchGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomMatchGroup.Unmarshal(m, b)
}
func (m *CustomMatchGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomMatchGroup.Marshal(b, m, deterministic)
}
func (m *CustomMatchGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomMatchGroup.Merge(m, src)
}
func (m *CustomMatchGroup) XXX_Size() int {
	return xxx_messageInfo_CustomMatchGroup.Size(m)
}
func (m *CustomMatchGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomMatchGroup.DiscardUnknown(m)
}

var xxx_messageInfo_CustomMatchGroup proto.InternalMessageInfo

func (m *CustomMatchGroup) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *CustomMatchGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomMatchGroup) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *CustomMatchGroup) GetPasswordRequired() bool {
	if m != nil {
		return m.PasswordRequired
	}
	return false
}

func (m *CustomMatchGroup) GetMaxUsers() uint32 {
	if m != nil {
		return m.MaxUsers
	}
	return 0
}

func (m *CustomMatchGroup) GetTotalUsers() uint32 {
	if m != nil {
		return m.TotalUsers
	}
	return 0
}

type JoinCustomMatchRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupPassword        uint64   `protobuf:"varint,3,opt,name=group_password,json=groupPassword,proto3" json:"group_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinCustomMatchRequest) Reset()         { *m = JoinCustomMatchRequest{} }
func (m *JoinCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*JoinCustomMatchRequest) ProtoMessage()    {}
func (*JoinCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{7}
}

func (m *JoinCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinCustomMatchRequest.Unmarshal(m, b)
}
func (m *JoinCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *JoinCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinCustomMatchRequest.Merge(m, src)
}
func (m *JoinCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_JoinCustomMatchRequest.Size(m)
}
func (m *JoinCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinCustomMatchRequest proto.InternalMessageInfo

func (m *JoinCustomMatchRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinCustomMatchRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *JoinCustomMatchRequest) GetGroupPassword() uint64 {
	if m != nil {
		return m.GroupPassword
	}
	return 0
}

type JoinCustomMatchResponse struct {
	Users                []uint64 `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	MaxUsers             uint32   `protobuf:"varint,2,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	Leader               uint64   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinCustomMatchResponse) Reset()         { *m = JoinCustomMatchResponse{} }
func (m *JoinCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*JoinCustomMatchResponse) ProtoMessage()    {}
func (*JoinCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{8}
}

func (m *JoinCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinCustomMatchResponse.Unmarshal(m, b)
}
func (m *JoinCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *JoinCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinCustomMatchResponse.Merge(m, src)
}
func (m *JoinCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_JoinCustomMatchResponse.Size(m)
}
func (m *JoinCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinCustomMatchResponse proto.InternalMessageInfo

func (m *JoinCustomMatchResponse) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *JoinCustomMatchResponse) GetMaxUsers() uint32 {
	if m != nil {
		return m.MaxUsers
	}
	return 0
}

func (m *JoinCustomMatchResponse) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

type LeaveCustomMatchRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveCustomMatchRequest) Reset()         { *m = LeaveCustomMatchRequest{} }
func (m *LeaveCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveCustomMatchRequest) ProtoMessage()    {}
func (*LeaveCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{9}
}

func (m *LeaveCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveCustomMatchRequest.Unmarshal(m, b)
}
func (m *LeaveCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *LeaveCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveCustomMatchRequest.Merge(m, src)
}
func (m *LeaveCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveCustomMatchRequest.Size(m)
}
func (m *LeaveCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveCustomMatchRequest proto.InternalMessageInfo

func (m *LeaveCustomMatchRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LeaveCustomMatchRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type LeaveCustomMatchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveCustomMatchResponse) Reset()         { *m = LeaveCustomMatchResponse{} }
func (m *LeaveCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveCustomMatchResponse) ProtoMessage()    {}
func (*LeaveCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{10}
}

func (m *LeaveCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveCustomMatchResponse.Unmarshal(m, b)
}
func (m *LeaveCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *LeaveCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveCustomMatchResponse.Merge(m, src)
}
func (m *LeaveCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveCustomMatchResponse.Size(m)
}
func (m *LeaveCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveCustomMatchResponse proto.InternalMessageInfo

type StartCustomMatchRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartCustomMatchRequest) Reset()         { *m = StartCustomMatchRequest{} }
func (m *StartCustomMatchRequest) String() string { return proto.CompactTextString(m) }
func (*StartCustomMatchRequest) ProtoMessage()    {}
func (*StartCustomMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{11}
}

func (m *StartCustomMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartCustomMatchRequest.Unmarshal(m, b)
}
func (m *StartCustomMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartCustomMatchRequest.Marshal(b, m, deterministic)
}
func (m *StartCustomMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartCustomMatchRequest.Merge(m, src)
}
func (m *StartCustomMatchRequest) XXX_Size() int {
	return xxx_messageInfo_StartCustomMatchRequest.Size(m)
}
func (m *StartCustomMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartCustomMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartCustomMatchRequest proto.InternalMessageInfo

func (m *StartCustomMatchRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StartCustomMatchRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type StartCustomMatchResponse struct {
	Users                []uint64 `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	Leader               uint64   `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	GroupId              int64    `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartCustomMatchResponse) Reset()         { *m = StartCustomMatchResponse{} }
func (m *StartCustomMatchResponse) String() string { return proto.CompactTextString(m) }
func (*StartCustomMatchResponse) ProtoMessage()    {}
func (*StartCustomMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb7dbeb9d4e0144, []int{12}
}

func (m *StartCustomMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartCustomMatchResponse.Unmarshal(m, b)
}
func (m *StartCustomMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartCustomMatchResponse.Marshal(b, m, deterministic)
}
func (m *StartCustomMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartCustomMatchResponse.Merge(m, src)
}
func (m *StartCustomMatchResponse) XXX_Size() int {
	return xxx_messageInfo_StartCustomMatchResponse.Size(m)
}
func (m *StartCustomMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartCustomMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartCustomMatchResponse proto.InternalMessageInfo

func (m *StartCustomMatchResponse) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *StartCustomMatchResponse) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *StartCustomMatchResponse) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*AddCustomMatchRequest)(nil), "pb.AddCustomMatchRequest")
	proto.RegisterType((*AddCustomMatchResponse)(nil), "pb.AddCustomMatchResponse")
	proto.RegisterType((*DeleteCustomMatchRequest)(nil), "pb.DeleteCustomMatchRequest")
	proto.RegisterType((*DeleteCustomMatchResponse)(nil), "pb.DeleteCustomMatchResponse")
	proto.RegisterType((*GetAllCustomMatchRequest)(nil), "pb.GetAllCustomMatchRequest")
	proto.RegisterType((*GetAllCustomMatchResponse)(nil), "pb.GetAllCustomMatchResponse")
	proto.RegisterType((*CustomMatchGroup)(nil), "pb.CustomMatchGroup")
	proto.RegisterType((*JoinCustomMatchRequest)(nil), "pb.JoinCustomMatchRequest")
	proto.RegisterType((*JoinCustomMatchResponse)(nil), "pb.JoinCustomMatchResponse")
	proto.RegisterType((*LeaveCustomMatchRequest)(nil), "pb.LeaveCustomMatchRequest")
	proto.RegisterType((*LeaveCustomMatchResponse)(nil), "pb.LeaveCustomMatchResponse")
	proto.RegisterType((*StartCustomMatchRequest)(nil), "pb.StartCustomMatchRequest")
	proto.RegisterType((*StartCustomMatchResponse)(nil), "pb.StartCustomMatchResponse")
}

func init() { proto.RegisterFile("custom_match.proto", fileDescriptor_6bb7dbeb9d4e0144) }

var fileDescriptor_6bb7dbeb9d4e0144 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x4d, 0xe9, 0xc7, 0xb2, 0x97, 0x60, 0xd6, 0x09, 0x42, 0x29, 0x6b, 0x24, 0x4d, 0x4c, 0x48,
	0x34, 0xc4, 0xac, 0xef, 0x26, 0xac, 0xbb, 0xd9, 0x60, 0xc4, 0x98, 0x31, 0x3e, 0x93, 0x81, 0x99,
	0x28, 0xb1, 0xa5, 0xdd, 0xce, 0x54, 0xf7, 0xc1, 0xdf, 0xe3, 0x2f, 0xf1, 0x87, 0x99, 0xf9, 0x00,
	0x5b, 0x98, 0xee, 0x13, 0x6f, 0xbd, 0xf7, 0x0c, 0xe7, 0x7e, 0x9c, 0x33, 0x03, 0xa0, 0x75, 0xc9,
	0x45, 0x96, 0x2e, 0x53, 0x22, 0xd6, 0xdf, 0xa7, 0x79, 0x91, 0x89, 0x0c, 0xb5, 0xf2, 0x55, 0xfc,
	0x1b, 0x9e, 0xcd, 0x28, 0x7d, 0xaf, 0xc0, 0x85, 0xc4, 0x30, 0xbb, 0x2f, 0x19, 0x17, 0xa8, 0x0f,
	0x41, 0xc2, 0x08, 0x65, 0x45, 0xe8, 0x8c, 0x9d, 0x89, 0x87, 0x4d, 0x84, 0x10, 0x78, 0x5b, 0x92,
	0xb2, 0xb0, 0x35, 0x76, 0x26, 0xe7, 0x58, 0x7d, 0xa3, 0x08, 0xda, 0x39, 0xe1, 0xfc, 0x57, 0x56,
	0xd0, 0xd0, 0x55, 0xf9, 0x7d, 0x8c, 0x46, 0x70, 0x9e, 0x92, 0x87, 0x65, 0xc9, 0x59, 0xc1, 0x43,
	0x6f, 0xec, 0x4c, 0xba, 0xb8, 0x9d, 0x92, 0x87, 0xaf, 0x32, 0x8e, 0xd7, 0xd0, 0x3f, 0xac, 0xce,
	0xf3, 0x6c, 0xcb, 0x19, 0xea, 0x81, 0xaf, 0x7f, 0xe2, 0x8c, 0xdd, 0x89, 0x87, 0x75, 0x50, 0x27,
	0x6b, 0xd5, 0xc9, 0x2a, 0x1d, 0xbb, 0xd5, 0x8e, 0xe3, 0x4f, 0x10, 0xde, 0xb0, 0x84, 0x09, 0x66,
	0x99, 0x72, 0x00, 0x67, 0x92, 0x6c, 0xb9, 0xa1, 0xbb, 0x31, 0x65, 0x38, 0xa7, 0x68, 0x08, 0xed,
	0x6f, 0x45, 0x56, 0xe6, 0x12, 0x91, 0x85, 0x5c, 0x7c, 0xa6, 0xe2, 0x39, 0x8d, 0x47, 0x30, 0xb4,
	0xf0, 0xe9, 0xbe, 0xe3, 0x1b, 0x08, 0xef, 0x98, 0x98, 0x25, 0x89, 0xa5, 0x58, 0x0f, 0x7c, 0x91,
	0x09, 0x92, 0xa8, 0x52, 0x5d, 0xac, 0x03, 0xb9, 0x50, 0xfe, 0x63, 0x93, 0x9b, 0x71, 0xd4, 0x77,
	0x3c, 0x87, 0xa1, 0x85, 0xc5, 0xac, 0xe6, 0x35, 0x04, 0xaa, 0x15, 0xbd, 0x9b, 0xce, 0x55, 0x6f,
	0x9a, 0xaf, 0xa6, 0x95, 0x83, 0x77, 0x12, 0xc4, 0xe6, 0x4c, 0xfc, 0xd7, 0x81, 0x8b, 0x43, 0xb0,
	0x36, 0x9d, 0x53, 0x9b, 0xce, 0xaa, 0x6f, 0xc3, 0x66, 0xd1, 0x2b, 0x78, 0xba, 0xd3, 0x79, 0x59,
	0xb0, 0xfb, 0x72, 0x53, 0x30, 0xaa, 0x34, 0x6e, 0xe3, 0x8b, 0x1d, 0x80, 0x4d, 0xbe, 0xae, 0x9d,
	0x7f, 0xa0, 0xdd, 0x0b, 0xe8, 0xa8, 0x6d, 0x18, 0x38, 0x50, 0x30, 0xa8, 0x94, 0x76, 0x0a, 0x87,
	0xfe, 0x87, 0x6c, 0xb3, 0x3d, 0x8d, 0x84, 0xe8, 0x25, 0x3c, 0xd1, 0x50, 0xcd, 0xb6, 0x1e, 0xee,
	0xaa, 0xec, 0x67, 0x93, 0x8c, 0x29, 0x0c, 0x8e, 0x8a, 0x9e, 0xde, 0x9f, 0x0b, 0x18, 0x7c, 0x64,
	0xe4, 0xe7, 0xa9, 0xec, 0x19, 0x41, 0x78, 0x4c, 0x67, 0xdc, 0xb9, 0x80, 0xc1, 0x17, 0x41, 0x0a,
	0x71, 0xa2, 0x52, 0x6b, 0x08, 0x8f, 0xe9, 0x1e, 0x5d, 0xd0, 0xff, 0x1d, 0xb4, 0x6a, 0x4e, 0xaa,
	0x16, 0x71, 0x6b, 0x45, 0xae, 0xfe, 0xb8, 0xd0, 0xa9, 0x14, 0x40, 0xef, 0xc0, 0x9d, 0x51, 0x8a,
	0x86, 0xd2, 0xf5, 0xd6, 0xa7, 0x2b, 0x8a, 0x6c, 0x90, 0x6e, 0xeb, 0x8d, 0x83, 0x6e, 0x21, 0xd0,
	0xd7, 0x17, 0x5d, 0xca, 0x73, 0x4d, 0x4f, 0x43, 0xf4, 0xbc, 0x01, 0x35, 0xf3, 0xdd, 0x42, 0xa0,
	0xaf, 0xa8, 0xa6, 0x69, 0xba, 0xf4, 0x9a, 0xa6, 0xf9, 0x32, 0xcf, 0xc0, 0x93, 0x16, 0x43, 0xaa,
	0x67, 0xbb, 0xc3, 0xa3, 0x91, 0x15, 0xdb, 0x0f, 0x74, 0x0d, 0xbe, 0x12, 0x1c, 0xa9, 0x73, 0x0d,
	0x56, 0x8a, 0x2e, 0xed, 0xa0, 0x69, 0xe3, 0x1a, 0x7c, 0xa5, 0xa4, 0xe6, 0x68, 0xf0, 0x88, 0xe6,
	0x68, 0x52, 0x7c, 0x15, 0xa8, 0x7f, 0x95, 0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0x2a,
	0x3f, 0xe8, 0x6b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomMatchClient is the client API for CustomMatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomMatchClient interface {
	Add(ctx context.Context, in *AddCustomMatchRequest, opts ...grpc.CallOption) (CustomMatch_AddClient, error)
	Delete(ctx context.Context, in *DeleteCustomMatchRequest, opts ...grpc.CallOption) (*DeleteCustomMatchResponse, error)
	GetAll(ctx context.Context, in *GetAllCustomMatchRequest, opts ...grpc.CallOption) (*GetAllCustomMatchResponse, error)
	Join(ctx context.Context, in *JoinCustomMatchRequest, opts ...grpc.CallOption) (CustomMatch_JoinClient, error)
	Leave(ctx context.Context, in *LeaveCustomMatchRequest, opts ...grpc.CallOption) (*LeaveCustomMatchResponse, error)
	Start(ctx context.Context, in *StartCustomMatchRequest, opts ...grpc.CallOption) (*StartCustomMatchResponse, error)
}

type customMatchClient struct {
	cc *grpc.ClientConn
}

func NewCustomMatchClient(cc *grpc.ClientConn) CustomMatchClient {
	return &customMatchClient{cc}
}

func (c *customMatchClient) Add(ctx context.Context, in *AddCustomMatchRequest, opts ...grpc.CallOption) (CustomMatch_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CustomMatch_serviceDesc.Streams[0], "/pb.CustomMatch/Add", opts...)
	if err != nil {
		return nil, err
	}
	x := &customMatchAddClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CustomMatch_AddClient interface {
	Recv() (*AddCustomMatchResponse, error)
	grpc.ClientStream
}

type customMatchAddClient struct {
	grpc.ClientStream
}

func (x *customMatchAddClient) Recv() (*AddCustomMatchResponse, error) {
	m := new(AddCustomMatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customMatchClient) Delete(ctx context.Context, in *DeleteCustomMatchRequest, opts ...grpc.CallOption) (*DeleteCustomMatchResponse, error) {
	out := new(DeleteCustomMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomMatch/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customMatchClient) GetAll(ctx context.Context, in *GetAllCustomMatchRequest, opts ...grpc.CallOption) (*GetAllCustomMatchResponse, error) {
	out := new(GetAllCustomMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomMatch/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customMatchClient) Join(ctx context.Context, in *JoinCustomMatchRequest, opts ...grpc.CallOption) (CustomMatch_JoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CustomMatch_serviceDesc.Streams[1], "/pb.CustomMatch/Join", opts...)
	if err != nil {
		return nil, err
	}
	x := &customMatchJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CustomMatch_JoinClient interface {
	Recv() (*JoinCustomMatchResponse, error)
	grpc.ClientStream
}

type customMatchJoinClient struct {
	grpc.ClientStream
}

func (x *customMatchJoinClient) Recv() (*JoinCustomMatchResponse, error) {
	m := new(JoinCustomMatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customMatchClient) Leave(ctx context.Context, in *LeaveCustomMatchRequest, opts ...grpc.CallOption) (*LeaveCustomMatchResponse, error) {
	out := new(LeaveCustomMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomMatch/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customMatchClient) Start(ctx context.Context, in *StartCustomMatchRequest, opts ...grpc.CallOption) (*StartCustomMatchResponse, error) {
	out := new(StartCustomMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomMatch/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomMatchServer is the server API for CustomMatch service.
type CustomMatchServer interface {
	Add(*AddCustomMatchRequest, CustomMatch_AddServer) error
	Delete(context.Context, *DeleteCustomMatchRequest) (*DeleteCustomMatchResponse, error)
	GetAll(context.Context, *GetAllCustomMatchRequest) (*GetAllCustomMatchResponse, error)
	Join(*JoinCustomMatchRequest, CustomMatch_JoinServer) error
	Leave(context.Context, *LeaveCustomMatchRequest) (*LeaveCustomMatchResponse, error)
	Start(context.Context, *StartCustomMatchRequest) (*StartCustomMatchResponse, error)
}

// UnimplementedCustomMatchServer can be embedded to have forward compatible implementations.
type UnimplementedCustomMatchServer struct {
}

func (*UnimplementedCustomMatchServer) Add(req *AddCustomMatchRequest, srv CustomMatch_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCustomMatchServer) Delete(ctx context.Context, req *DeleteCustomMatchRequest) (*DeleteCustomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCustomMatchServer) GetAll(ctx context.Context, req *GetAllCustomMatchRequest) (*GetAllCustomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedCustomMatchServer) Join(req *JoinCustomMatchRequest, srv CustomMatch_JoinServer) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedCustomMatchServer) Leave(ctx context.Context, req *LeaveCustomMatchRequest) (*LeaveCustomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (*UnimplementedCustomMatchServer) Start(ctx context.Context, req *StartCustomMatchRequest) (*StartCustomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}

func RegisterCustomMatchServer(s *grpc.Server, srv CustomMatchServer) {
	s.RegisterService(&_CustomMatch_serviceDesc, srv)
}

func _CustomMatch_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddCustomMatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomMatchServer).Add(m, &customMatchAddServer{stream})
}

type CustomMatch_AddServer interface {
	Send(*AddCustomMatchResponse) error
	grpc.ServerStream
}

type customMatchAddServer struct {
	grpc.ServerStream
}

func (x *customMatchAddServer) Send(m *AddCustomMatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CustomMatch_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomMatchServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomMatch/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomMatchServer).Delete(ctx, req.(*DeleteCustomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomMatch_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCustomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomMatchServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomMatch/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomMatchServer).GetAll(ctx, req.(*GetAllCustomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomMatch_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinCustomMatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomMatchServer).Join(m, &customMatchJoinServer{stream})
}

type CustomMatch_JoinServer interface {
	Send(*JoinCustomMatchResponse) error
	grpc.ServerStream
}

type customMatchJoinServer struct {
	grpc.ServerStream
}

func (x *customMatchJoinServer) Send(m *JoinCustomMatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CustomMatch_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveCustomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomMatchServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomMatch/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomMatchServer).Leave(ctx, req.(*LeaveCustomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomMatch_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCustomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomMatchServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomMatch/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomMatchServer).Start(ctx, req.(*StartCustomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomMatch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CustomMatch",
	HandlerType: (*CustomMatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _CustomMatch_Delete_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CustomMatch_GetAll_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _CustomMatch_Leave_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _CustomMatch_Start_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Add",
			Handler:       _CustomMatch_Add_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Join",
			Handler:       _CustomMatch_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "custom_match.proto",
}
