// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHistoryRequest struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryRequest) Reset()         { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()    {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{0}
}

func (m *GetHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryRequest.Unmarshal(m, b)
}
func (m *GetHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryRequest.Merge(m, src)
}
func (m *GetHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetHistoryRequest.Size(m)
}
func (m *GetHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryRequest proto.InternalMessageInfo

func (m *GetHistoryRequest) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetHistoryResponse struct {
	Match                []*MatchHistoryInfo `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetHistoryResponse) Reset()         { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()    {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{1}
}

func (m *GetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryResponse.Unmarshal(m, b)
}
func (m *GetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryResponse.Merge(m, src)
}
func (m *GetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoryResponse.Size(m)
}
func (m *GetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryResponse proto.InternalMessageInfo

func (m *GetHistoryResponse) GetMatch() []*MatchHistoryInfo {
	if m != nil {
		return m.Match
	}
	return nil
}

type GetUserHistoryRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserHistoryRequest) Reset()         { *m = GetUserHistoryRequest{} }
func (m *GetUserHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserHistoryRequest) ProtoMessage()    {}
func (*GetUserHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{2}
}

func (m *GetUserHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserHistoryRequest.Unmarshal(m, b)
}
func (m *GetUserHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetUserHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserHistoryRequest.Merge(m, src)
}
func (m *GetUserHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserHistoryRequest.Size(m)
}
func (m *GetUserHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserHistoryRequest proto.InternalMessageInfo

func (m *GetUserHistoryRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserHistoryRequest) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetUserHistoryResponse struct {
	UserId               uint64              `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Match                []*MatchHistoryInfo `protobuf:"bytes,2,rep,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetUserHistoryResponse) Reset()         { *m = GetUserHistoryResponse{} }
func (m *GetUserHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserHistoryResponse) ProtoMessage()    {}
func (*GetUserHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{3}
}

func (m *GetUserHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserHistoryResponse.Unmarshal(m, b)
}
func (m *GetUserHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetUserHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserHistoryResponse.Merge(m, src)
}
func (m *GetUserHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserHistoryResponse.Size(m)
}
func (m *GetUserHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserHistoryResponse proto.InternalMessageInfo

func (m *GetUserHistoryResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserHistoryResponse) GetMatch() []*MatchHistoryInfo {
	if m != nil {
		return m.Match
	}
	return nil
}

type MatchHistoryInfo struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Winner               *TeamHistoryInfo     `protobuf:"bytes,2,opt,name=Winner,proto3" json:"Winner,omitempty"`
	Loser                *TeamHistoryInfo     `protobuf:"bytes,3,opt,name=Loser,proto3" json:"Loser,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MatchHistoryInfo) Reset()         { *m = MatchHistoryInfo{} }
func (m *MatchHistoryInfo) String() string { return proto.CompactTextString(m) }
func (*MatchHistoryInfo) ProtoMessage()    {}
func (*MatchHistoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{4}
}

func (m *MatchHistoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchHistoryInfo.Unmarshal(m, b)
}
func (m *MatchHistoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchHistoryInfo.Marshal(b, m, deterministic)
}
func (m *MatchHistoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchHistoryInfo.Merge(m, src)
}
func (m *MatchHistoryInfo) XXX_Size() int {
	return xxx_messageInfo_MatchHistoryInfo.Size(m)
}
func (m *MatchHistoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchHistoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchHistoryInfo proto.InternalMessageInfo

func (m *MatchHistoryInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchHistoryInfo) GetWinner() *TeamHistoryInfo {
	if m != nil {
		return m.Winner
	}
	return nil
}

func (m *MatchHistoryInfo) GetLoser() *TeamHistoryInfo {
	if m != nil {
		return m.Loser
	}
	return nil
}

func (m *MatchHistoryInfo) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type TeamHistoryInfo struct {
	Users                []uint64 `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	Score                uint32   `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamHistoryInfo) Reset()         { *m = TeamHistoryInfo{} }
func (m *TeamHistoryInfo) String() string { return proto.CompactTextString(m) }
func (*TeamHistoryInfo) ProtoMessage()    {}
func (*TeamHistoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{5}
}

func (m *TeamHistoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamHistoryInfo.Unmarshal(m, b)
}
func (m *TeamHistoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamHistoryInfo.Marshal(b, m, deterministic)
}
func (m *TeamHistoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamHistoryInfo.Merge(m, src)
}
func (m *TeamHistoryInfo) XXX_Size() int {
	return xxx_messageInfo_TeamHistoryInfo.Size(m)
}
func (m *TeamHistoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamHistoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeamHistoryInfo proto.InternalMessageInfo

func (m *TeamHistoryInfo) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *TeamHistoryInfo) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*GetHistoryRequest)(nil), "pb.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "pb.GetHistoryResponse")
	proto.RegisterType((*GetUserHistoryRequest)(nil), "pb.GetUserHistoryRequest")
	proto.RegisterType((*GetUserHistoryResponse)(nil), "pb.GetUserHistoryResponse")
	proto.RegisterType((*MatchHistoryInfo)(nil), "pb.MatchHistoryInfo")
	proto.RegisterType((*TeamHistoryInfo)(nil), "pb.TeamHistoryInfo")
}

func init() { proto.RegisterFile("history.proto", fileDescriptor_454388b49b309873) }

var fileDescriptor_454388b49b309873 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xd3, 0x52, 0x20, 0x19, 0xc2, 0xfb, 0xea, 0x0a, 0x58, 0x7b, 0x91, 0xf4, 0x04, 0x9a,
	0x2c, 0x09, 0x7a, 0x35, 0xe1, 0x24, 0x92, 0xe8, 0xa5, 0xc1, 0x78, 0x32, 0xa6, 0x85, 0x01, 0x9a,
	0xd0, 0x6e, 0xdd, 0x5d, 0x0e, 0x1e, 0xfd, 0x3a, 0x7e, 0x4a, 0xb3, 0x7f, 0x40, 0x52, 0x24, 0x1e,
	0x67, 0xf6, 0xb7, 0xcf, 0x3e, 0x33, 0xcf, 0x42, 0x73, 0x95, 0x0a, 0xc9, 0xf8, 0x07, 0x2d, 0x38,
	0x93, 0x8c, 0xb8, 0x45, 0x12, 0x5c, 0x2e, 0x19, 0x5b, 0xae, 0x71, 0xa0, 0x3b, 0xc9, 0x66, 0x31,
	0x90, 0x69, 0x86, 0x42, 0xc6, 0x59, 0x61, 0xa0, 0xb0, 0x0f, 0xa7, 0x63, 0x94, 0x0f, 0xe6, 0x62,
	0x84, 0xef, 0x1b, 0x14, 0x92, 0xb4, 0xa0, 0x2a, 0x99, 0x8c, 0xd7, 0xbe, 0xd3, 0x75, 0x7a, 0xcd,
	0xc8, 0x14, 0xe1, 0x08, 0xc8, 0x3e, 0x2a, 0x0a, 0x96, 0x0b, 0x24, 0x57, 0x50, 0xcd, 0x62, 0x39,
	0x5b, 0xf9, 0x4e, 0xb7, 0xd2, 0x6b, 0x0c, 0x5b, 0xb4, 0x48, 0xe8, 0x93, 0x6a, 0x58, 0x70, 0x92,
	0x2f, 0x58, 0x64, 0x90, 0xf0, 0x1e, 0xda, 0x63, 0x94, 0xcf, 0x02, 0x79, 0xe9, 0xc1, 0x73, 0xa8,
	0x6f, 0x04, 0xf2, 0xb7, 0x74, 0xae, 0x9f, 0xf4, 0xa2, 0x9a, 0x2a, 0x27, 0xf3, 0x1f, 0x27, 0xee,
	0xbe, 0x93, 0x57, 0xe8, 0x94, 0x75, 0xac, 0x9b, 0xa3, 0x42, 0x3b, 0x9b, 0xee, 0xdf, 0x36, 0xbf,
	0x1c, 0x38, 0x29, 0x9f, 0x91, 0x7f, 0xe0, 0xee, 0x44, 0xdd, 0x74, 0x4e, 0xae, 0xa1, 0xf6, 0x92,
	0xe6, 0x39, 0x72, 0x6d, 0xad, 0x31, 0x3c, 0x53, 0x8a, 0x53, 0x8c, 0xb3, 0x7d, 0x41, 0x8b, 0x90,
	0x3e, 0x54, 0x1f, 0x99, 0x40, 0xee, 0x57, 0x8e, 0xb3, 0x86, 0x20, 0x14, 0x3c, 0x95, 0x91, 0xef,
	0x69, 0x32, 0xa0, 0x26, 0x40, 0xba, 0x0d, 0x90, 0x4e, 0xb7, 0x01, 0x46, 0x9a, 0x0b, 0xef, 0xe0,
	0x7f, 0x49, 0x49, 0x2d, 0x4d, 0x4d, 0x2d, 0x74, 0x24, 0x5e, 0x64, 0x0a, 0xd5, 0x15, 0x33, 0xc6,
	0x71, 0xbb, 0x4a, 0x5d, 0x0c, 0x3f, 0x1d, 0xa8, 0xdb, 0xbb, 0xe4, 0x16, 0x2a, 0x63, 0x94, 0xa4,
	0xad, 0xdc, 0x1d, 0x7c, 0x8a, 0xa0, 0x53, 0x6e, 0xdb, 0x95, 0x8f, 0xa0, 0x6e, 0xc3, 0x20, 0x17,
	0x16, 0x39, 0x4c, 0x38, 0x08, 0x7e, 0x3b, 0x32, 0x0a, 0x49, 0x4d, 0x0f, 0x77, 0xf3, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x69, 0x9e, 0x6e, 0x45, 0xc0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryClient interface {
	Get(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	GetUser(ctx context.Context, in *GetUserHistoryRequest, opts ...grpc.CallOption) (*GetUserHistoryResponse, error)
}

type historyClient struct {
	cc *grpc.ClientConn
}

func NewHistoryClient(cc *grpc.ClientConn) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) Get(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, "/pb.History/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) GetUser(ctx context.Context, in *GetUserHistoryRequest, opts ...grpc.CallOption) (*GetUserHistoryResponse, error) {
	out := new(GetUserHistoryResponse)
	err := c.cc.Invoke(ctx, "/pb.History/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
type HistoryServer interface {
	Get(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	GetUser(context.Context, *GetUserHistoryRequest) (*GetUserHistoryResponse, error)
}

// UnimplementedHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (*UnimplementedHistoryServer) Get(ctx context.Context, req *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedHistoryServer) GetUser(ctx context.Context, req *GetUserHistoryRequest) (*GetUserHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterHistoryServer(s *grpc.Server, srv HistoryServer) {
	s.RegisterService(&_History_serviceDesc, srv)
}

func _History_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.History/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Get(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.History/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).GetUser(ctx, req.(*GetUserHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _History_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _History_Get_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _History_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
