// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ranking.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRankingRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRankingRequest) Reset()         { *m = GetRankingRequest{} }
func (m *GetRankingRequest) String() string { return proto.CompactTextString(m) }
func (*GetRankingRequest) ProtoMessage()    {}
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{0}
}

func (m *GetRankingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRankingRequest.Unmarshal(m, b)
}
func (m *GetRankingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRankingRequest.Marshal(b, m, deterministic)
}
func (m *GetRankingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRankingRequest.Merge(m, src)
}
func (m *GetRankingRequest) XXX_Size() int {
	return xxx_messageInfo_GetRankingRequest.Size(m)
}
func (m *GetRankingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRankingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRankingRequest proto.InternalMessageInfo

func (m *GetRankingRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetRankingResponse struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating               uint64   `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Rank                 uint64   `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRankingResponse) Reset()         { *m = GetRankingResponse{} }
func (m *GetRankingResponse) String() string { return proto.CompactTextString(m) }
func (*GetRankingResponse) ProtoMessage()    {}
func (*GetRankingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{1}
}

func (m *GetRankingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRankingResponse.Unmarshal(m, b)
}
func (m *GetRankingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRankingResponse.Marshal(b, m, deterministic)
}
func (m *GetRankingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRankingResponse.Merge(m, src)
}
func (m *GetRankingResponse) XXX_Size() int {
	return xxx_messageInfo_GetRankingResponse.Size(m)
}
func (m *GetRankingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRankingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRankingResponse proto.InternalMessageInfo

func (m *GetRankingResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetRankingResponse) GetRating() uint64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *GetRankingResponse) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type GetTopRankingRequest struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip                 uint64   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopRankingRequest) Reset()         { *m = GetTopRankingRequest{} }
func (m *GetTopRankingRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopRankingRequest) ProtoMessage()    {}
func (*GetTopRankingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{2}
}

func (m *GetTopRankingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopRankingRequest.Unmarshal(m, b)
}
func (m *GetTopRankingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopRankingRequest.Marshal(b, m, deterministic)
}
func (m *GetTopRankingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopRankingRequest.Merge(m, src)
}
func (m *GetTopRankingRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopRankingRequest.Size(m)
}
func (m *GetTopRankingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopRankingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopRankingRequest proto.InternalMessageInfo

func (m *GetTopRankingRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTopRankingRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type GetTopRankingResponse struct {
	Ratings              []*GetRankingResponse `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetTopRankingResponse) Reset()         { *m = GetTopRankingResponse{} }
func (m *GetTopRankingResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopRankingResponse) ProtoMessage()    {}
func (*GetTopRankingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{3}
}

func (m *GetTopRankingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopRankingResponse.Unmarshal(m, b)
}
func (m *GetTopRankingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopRankingResponse.Marshal(b, m, deterministic)
}
func (m *GetTopRankingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopRankingResponse.Merge(m, src)
}
func (m *GetTopRankingResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopRankingResponse.Size(m)
}
func (m *GetTopRankingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopRankingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopRankingResponse proto.InternalMessageInfo

func (m *GetTopRankingResponse) GetRatings() []*GetRankingResponse {
	if m != nil {
		return m.Ratings
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRankingRequest)(nil), "pb.GetRankingRequest")
	proto.RegisterType((*GetRankingResponse)(nil), "pb.GetRankingResponse")
	proto.RegisterType((*GetTopRankingRequest)(nil), "pb.GetTopRankingRequest")
	proto.RegisterType((*GetTopRankingResponse)(nil), "pb.GetTopRankingResponse")
}

func init() { proto.RegisterFile("ranking.proto", fileDescriptor_097e8f966f16a890) }

var fileDescriptor_097e8f966f16a890 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x76, 0x4d, 0x61, 0xc4, 0x83, 0xc3, 0xee, 0x1a, 0xf7, 0xb4, 0xe4, 0xb4, 0x07,
	0x29, 0xb2, 0x7a, 0x15, 0xbc, 0x95, 0xbd, 0x06, 0x2f, 0x9e, 0xa4, 0xa5, 0xa1, 0x84, 0x6a, 0x12,
	0x93, 0xf4, 0xea, 0x6f, 0x97, 0x26, 0x11, 0xa4, 0xdd, 0xde, 0x66, 0xde, 0xbc, 0x79, 0xf9, 0x86,
	0xc0, 0x8d, 0xad, 0x55, 0x2f, 0x55, 0x57, 0x1a, 0xab, 0xbd, 0xc6, 0x95, 0x69, 0xd8, 0x03, 0xdc,
	0x56, 0xc2, 0xf3, 0xa8, 0x73, 0xf1, 0x3d, 0x08, 0xe7, 0xf1, 0x0e, 0x8a, 0xc1, 0x09, 0xfb, 0x21,
	0x5b, 0x9a, 0x1d, 0xb2, 0xe3, 0x9a, 0x93, 0xb1, 0x3d, 0xb7, 0xec, 0x1d, 0xf0, 0xbf, 0xdb, 0x19,
	0xad, 0x9c, 0x58, 0xb4, 0xe3, 0x0e, 0x88, 0xad, 0xbd, 0x54, 0x1d, 0x5d, 0x45, 0x3d, 0x76, 0x88,
	0xb0, 0x1e, 0x49, 0x68, 0x1e, 0xd4, 0x50, 0xb3, 0x57, 0xd8, 0x54, 0xc2, 0xbf, 0x69, 0x33, 0x61,
	0xd9, 0xc0, 0xd5, 0xa7, 0xfc, 0x92, 0x3e, 0x45, 0xc7, 0x66, 0x4c, 0x70, 0xbd, 0x34, 0x29, 0x37,
	0xd4, 0xec, 0x0c, 0xdb, 0x49, 0x42, 0xe2, 0x7b, 0x84, 0x22, 0x3e, 0xec, 0x68, 0x76, 0xc8, 0x8f,
	0xd7, 0xa7, 0x5d, 0x69, 0x9a, 0x72, 0x7e, 0x08, 0xff, 0xb3, 0x9d, 0x7e, 0xa0, 0x48, 0x33, 0x7c,
	0x86, 0xbc, 0x12, 0x1e, 0xb7, 0xd3, 0x95, 0x40, 0xb7, 0x5f, 0x48, 0xc2, 0x17, 0x20, 0x91, 0x05,
	0x69, 0x72, 0xcc, 0x2e, 0xdb, 0xdf, 0x5f, 0x98, 0xc4, 0xf5, 0x86, 0x84, 0x0f, 0x7a, 0xfa, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xe8, 0x56, 0x3f, 0x20, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankingClient is the client API for Ranking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankingClient interface {
	Get(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	GetTop(ctx context.Context, in *GetTopRankingRequest, opts ...grpc.CallOption) (*GetTopRankingResponse, error)
}

type rankingClient struct {
	cc *grpc.ClientConn
}

func NewRankingClient(cc *grpc.ClientConn) RankingClient {
	return &rankingClient{cc}
}

func (c *rankingClient) Get(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, "/pb.Ranking/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetTop(ctx context.Context, in *GetTopRankingRequest, opts ...grpc.CallOption) (*GetTopRankingResponse, error) {
	out := new(GetTopRankingResponse)
	err := c.cc.Invoke(ctx, "/pb.Ranking/GetTop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServer is the server API for Ranking service.
type RankingServer interface {
	Get(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	GetTop(context.Context, *GetTopRankingRequest) (*GetTopRankingResponse, error)
}

// UnimplementedRankingServer can be embedded to have forward compatible implementations.
type UnimplementedRankingServer struct {
}

func (*UnimplementedRankingServer) Get(ctx context.Context, req *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRankingServer) GetTop(ctx context.Context, req *GetTopRankingRequest) (*GetTopRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTop not implemented")
}

func RegisterRankingServer(s *grpc.Server, srv RankingServer) {
	s.RegisterService(&_Ranking_serviceDesc, srv)
}

func _Ranking_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ranking/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).Get(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ranking/GetTop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetTop(ctx, req.(*GetTopRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ranking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ranking",
	HandlerType: (*RankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Ranking_Get_Handler,
		},
		{
			MethodName: "GetTop",
			Handler:    _Ranking_GetTop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}
